{% set name = "openmm-atmmetaforce-plugin" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Gallicchio-Lab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9404a368c0d7b3e131904f23146b405c7913ede8009ef0584246ae7c889d2652

build:
  number: 1
  skip: true  # [not linux64 and not win64]
  skip: true  # [cuda_compiler_version in (undefined, 'None')]
  run_exports:
    # TODO: Relax max_pin at version 1.0 / stable API
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - ninja  # [win]
    - cmake
    - swig <4.1

  host:
    - python
    - openmm
    - pthread-stubs
    - lxml

  run:
    - python
    - numpy
    # openmm package is missing a run_export as of 9 June 2022
    - {{ pin_compatible('openmm') }}

test:
  requires:
    - pocl  # [unix]
    - pip
  imports:
    - simtk
    - openmm
    - numpy

about:
  home: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin.git
  license: LGPL-2.0-only
  license_family: LGPL
  license_file:
    - LICENSE
  summary: The Alchemical Transfer Method Plugin for OpenMM
  description: |
    This plugin implements the Alchemical Transfer Potential (ATM) for the calculation
    of absolute and relative binding free energies of molecular complexes
    in OpenMM, a high performance toolkit for molecular simulation.
  doc_url: https://github.com/Gallicchio-Lab/async_re-openmm/tree/master/examples
  dev_url: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin.git

extra:
  recipe-maintainers:
    - egallicc
